
spring.application.name=UrbanEye Backend

server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false


app.jwt.secret=${JWT_SECRET:VXJiYW5FeWVBSVNlY3JldEtleUZvckpXVEF1dGhlbnRpY2F0aW9uQmFja2VuZDIwMjY=}
app.jwt.expiration=${JWT_EXPIRATION:86400000}

#google.maps.api.key=${GOOGLE_MAPS_KEY:AIzaSyAoSq2HEgrT_CoqC5Ra1PYeDCyu96WTyx0}
weather.api.key=${WEATHER_API_KEY:mock_key}


logging.level.com.urbaneye=INFO
logging.level.org.springframework.security=WARN
logging.level.org.hibernate=WARN

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Asia/Kolkata
